---
- include_vars: ../../vars_main.yml

- name: Descargar docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/{{ version_compose }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '+x'

