---
- name: Descargar docker-compose 
  get_url:
    url : https://github.com/docker/compose/releases/download/{{ version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '+x'

