---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Agrega la llave GPG de Docker
  ansible.builtin.apt_key:
    url: "{{ gpg_docker }}"
    state: present

- name:  Agrega el repo
  ansible.builtin.apt_repository:
    repo: "deb {{ repo_docker }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-sources

- name: Instalación de dependencias
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  with_items: "{{ docker_packages }}"

- name: Instalación de dependencias pip
  ansible.builtin.pip:
    name: docker-compose  

- name: Agrega usuario a grupo Docker
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true