---
- include_vars: ../../vars_main.yml

- name: Instalación de dependencias
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ docker_packages }}"

- name: Agrega la llave GPG de Docker
  apt_key:
    url: "{{ gpg_docker }}"
    state: present

- name:  Agrega el repo
  apt_repository:
    repo: deb "{{ repo_docker }}" focal stable
    state: present

- name: Instalación de docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Agrega usuario "{{ usuario }}" a grupo Docker
  user:
    name: '{{ usuario }}'
    groups: docker
    append: true