---
- include_vars: ../../vars_main.yml

- name: Instalación de dependencias
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes
    cache_valid_time: 3600

- name: Agrega la llave GPG de Docker
  apt_key:
    url: "{{ gpg_docker }}"
    state: present

- name:  Agrega el repo
  apt_repository:
    repo: deb "{{ repo_docker }}" focal stable
    state: present

- name: Instalación de docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Agrega usuario "{{ usuario }}" a grupo Docker
  user:
    name: '{{ usuario }}'
    groups: docker
    append: yes